// @generated by generate.py — DO NOT EDIT BY HAND.
// Mechanical Kani harnesses for vstd assume_specification contracts.
// See generate.py for the translation rules and GENERATED_REPORT.md
// for coverage and per-item skip reasons.
#![allow(unused, clippy::all)]

#[cfg(kani)]
#[kani::proof]
fn gen_i16_checked_add() {
    // num.rs:404  <i16>::checked_add   (verus.git std_specs)
    let x: i16 = kani::any();
    let y: i16 = kani::any();
    let spec: Option<i16> = if ((((x as i128)) + ((y as i128))) > ((i16::MAX as i128))) || ((((x as i128)) + ((y as i128))) < ((i16::MIN as i128))) { None } else { Some((((x as i128)) + ((y as i128))) as i16) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i16_checked_add_unsigned() {
    // num.rs:416  <i16>::checked_add_unsigned   (verus.git std_specs)
    let x: i16 = kani::any();
    let y: u16 = kani::any();
    let spec: Option<i16> = if (((x as i128)) + ((y as i128))) > ((i16::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as i16) };
    assert_eq!(spec, x.checked_add_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i16_checked_mul() {
    // num.rs:452  <i16>::checked_mul   (verus.git std_specs)
    let x: i16 = kani::any();
    let y: i16 = kani::any();
    let spec: Option<i16> = if ((((x as i128)) * ((y as i128))) > ((i16::MAX as i128))) || ((((x as i128)) * ((y as i128))) < ((i16::MIN as i128))) { None } else { Some((((x as i128)) * ((y as i128))) as i16) };
    assert_eq!(spec, x.checked_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i16_checked_sub() {
    // num.rs:428  <i16>::checked_sub   (verus.git std_specs)
    let x: i16 = kani::any();
    let y: i16 = kani::any();
    let spec: Option<i16> = if ((((x as i128)) - ((y as i128))) > ((i16::MAX as i128))) || ((((x as i128)) - ((y as i128))) < ((i16::MIN as i128))) { None } else { Some((((x as i128)) - ((y as i128))) as i16) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i16_checked_sub_unsigned() {
    // num.rs:440  <i16>::checked_sub_unsigned   (verus.git std_specs)
    let x: i16 = kani::any();
    let y: u16 = kani::any();
    let spec: Option<i16> = if (((x as i128)) - ((y as i128))) < ((i16::MIN as i128)) { None } else { Some((((x as i128)) - ((y as i128))) as i16) };
    assert_eq!(spec, x.checked_sub_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i32_checked_add() {
    // num.rs:404  <i32>::checked_add   (verus.git std_specs)
    let x: i32 = kani::any();
    let y: i32 = kani::any();
    let spec: Option<i32> = if ((((x as i128)) + ((y as i128))) > ((i32::MAX as i128))) || ((((x as i128)) + ((y as i128))) < ((i32::MIN as i128))) { None } else { Some((((x as i128)) + ((y as i128))) as i32) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i32_checked_add_unsigned() {
    // num.rs:416  <i32>::checked_add_unsigned   (verus.git std_specs)
    let x: i32 = kani::any();
    let y: u32 = kani::any();
    let spec: Option<i32> = if (((x as i128)) + ((y as i128))) > ((i32::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as i32) };
    assert_eq!(spec, x.checked_add_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i32_checked_sub() {
    // num.rs:428  <i32>::checked_sub   (verus.git std_specs)
    let x: i32 = kani::any();
    let y: i32 = kani::any();
    let spec: Option<i32> = if ((((x as i128)) - ((y as i128))) > ((i32::MAX as i128))) || ((((x as i128)) - ((y as i128))) < ((i32::MIN as i128))) { None } else { Some((((x as i128)) - ((y as i128))) as i32) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i32_checked_sub_unsigned() {
    // num.rs:440  <i32>::checked_sub_unsigned   (verus.git std_specs)
    let x: i32 = kani::any();
    let y: u32 = kani::any();
    let spec: Option<i32> = if (((x as i128)) - ((y as i128))) < ((i32::MIN as i128)) { None } else { Some((((x as i128)) - ((y as i128))) as i32) };
    assert_eq!(spec, x.checked_sub_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i64_checked_add() {
    // num.rs:404  <i64>::checked_add   (verus.git std_specs)
    let x: i64 = kani::any();
    let y: i64 = kani::any();
    let spec: Option<i64> = if ((((x as i128)) + ((y as i128))) > ((i64::MAX as i128))) || ((((x as i128)) + ((y as i128))) < ((i64::MIN as i128))) { None } else { Some((((x as i128)) + ((y as i128))) as i64) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i64_checked_add_unsigned() {
    // num.rs:416  <i64>::checked_add_unsigned   (verus.git std_specs)
    let x: i64 = kani::any();
    let y: u64 = kani::any();
    let spec: Option<i64> = if (((x as i128)) + ((y as i128))) > ((i64::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as i64) };
    assert_eq!(spec, x.checked_add_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i64_checked_sub() {
    // num.rs:428  <i64>::checked_sub   (verus.git std_specs)
    let x: i64 = kani::any();
    let y: i64 = kani::any();
    let spec: Option<i64> = if ((((x as i128)) - ((y as i128))) > ((i64::MAX as i128))) || ((((x as i128)) - ((y as i128))) < ((i64::MIN as i128))) { None } else { Some((((x as i128)) - ((y as i128))) as i64) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i64_checked_sub_unsigned() {
    // num.rs:440  <i64>::checked_sub_unsigned   (verus.git std_specs)
    let x: i64 = kani::any();
    let y: u64 = kani::any();
    let spec: Option<i64> = if (((x as i128)) - ((y as i128))) < ((i64::MIN as i128)) { None } else { Some((((x as i128)) - ((y as i128))) as i64) };
    assert_eq!(spec, x.checked_sub_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_add() {
    // num.rs:404  <i8>::checked_add   (verus.git std_specs)
    let x: i8 = kani::any();
    let y: i8 = kani::any();
    let spec: Option<i8> = if ((((x as i128)) + ((y as i128))) > ((i8::MAX as i128))) || ((((x as i128)) + ((y as i128))) < ((i8::MIN as i128))) { None } else { Some((((x as i128)) + ((y as i128))) as i8) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_add_unsigned() {
    // num.rs:416  <i8>::checked_add_unsigned   (verus.git std_specs)
    let x: i8 = kani::any();
    let y: u8 = kani::any();
    let spec: Option<i8> = if (((x as i128)) + ((y as i128))) > ((i8::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as i8) };
    assert_eq!(spec, x.checked_add_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_div_euclid() {
    // num.rs:476  <i8>::checked_div_euclid   (verus.git std_specs)
    let lhs: i8 = kani::any();
    let rhs: i8 = kani::any();
    let spec: Option<i8> = if (((rhs as i128)) == (0i128)) || ((((lhs as i128)) == ((i8::MIN as i128))) && (((rhs as i128)) == (-(1i128)))) { None } else { Some((((lhs).div_euclid(rhs) as i128)) as i8) };
    assert_eq!(spec, lhs.checked_div_euclid(rhs));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_mul() {
    // num.rs:452  <i8>::checked_mul   (verus.git std_specs)
    let x: i8 = kani::any();
    let y: i8 = kani::any();
    let spec: Option<i8> = if ((((x as i128)) * ((y as i128))) > ((i8::MAX as i128))) || ((((x as i128)) * ((y as i128))) < ((i8::MIN as i128))) { None } else { Some((((x as i128)) * ((y as i128))) as i8) };
    assert_eq!(spec, x.checked_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_rem_euclid() {
    // num.rs:500  <i8>::checked_rem_euclid   (verus.git std_specs)
    let lhs: i8 = kani::any();
    let rhs: i8 = kani::any();
    let spec: Option<i8> = if (((rhs as i128)) == (0i128)) || ((((lhs as i128)) == ((i8::MIN as i128))) && (((rhs as i128)) == (-(1i128)))) { None } else { Some((((lhs).rem_euclid(rhs) as i128)) as i8) };
    assert_eq!(spec, lhs.checked_rem_euclid(rhs));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_sub() {
    // num.rs:428  <i8>::checked_sub   (verus.git std_specs)
    let x: i8 = kani::any();
    let y: i8 = kani::any();
    let spec: Option<i8> = if ((((x as i128)) - ((y as i128))) > ((i8::MAX as i128))) || ((((x as i128)) - ((y as i128))) < ((i8::MIN as i128))) { None } else { Some((((x as i128)) - ((y as i128))) as i8) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_i8_checked_sub_unsigned() {
    // num.rs:440  <i8>::checked_sub_unsigned   (verus.git std_specs)
    let x: i8 = kani::any();
    let y: u8 = kani::any();
    let spec: Option<i8> = if (((x as i128)) - ((y as i128))) < ((i8::MIN as i128)) { None } else { Some((((x as i128)) - ((y as i128))) as i8) };
    assert_eq!(spec, x.checked_sub_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_isize_checked_add() {
    // num.rs:404  <isize>::checked_add   (verus.git std_specs)
    let x: isize = kani::any();
    let y: isize = kani::any();
    let spec: Option<isize> = if ((((x as i128)) + ((y as i128))) > ((isize::MAX as i128))) || ((((x as i128)) + ((y as i128))) < ((isize::MIN as i128))) { None } else { Some((((x as i128)) + ((y as i128))) as isize) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_isize_checked_add_unsigned() {
    // num.rs:416  <isize>::checked_add_unsigned   (verus.git std_specs)
    let x: isize = kani::any();
    let y: usize = kani::any();
    let spec: Option<isize> = if (((x as i128)) + ((y as i128))) > ((isize::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as isize) };
    assert_eq!(spec, x.checked_add_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_isize_checked_sub() {
    // num.rs:428  <isize>::checked_sub   (verus.git std_specs)
    let x: isize = kani::any();
    let y: isize = kani::any();
    let spec: Option<isize> = if ((((x as i128)) - ((y as i128))) > ((isize::MAX as i128))) || ((((x as i128)) - ((y as i128))) < ((isize::MIN as i128))) { None } else { Some((((x as i128)) - ((y as i128))) as isize) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_isize_checked_sub_unsigned() {
    // num.rs:440  <isize>::checked_sub_unsigned   (verus.git std_specs)
    let x: isize = kani::any();
    let y: usize = kani::any();
    let spec: Option<isize> = if (((x as i128)) - ((y as i128))) < ((isize::MIN as i128)) { None } else { Some((((x as i128)) - ((y as i128))) as isize) };
    assert_eq!(spec, x.checked_sub_unsigned(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_checked_add() {
    // num.rs:140  <u16>::checked_add   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: Option<u16> = if (((x as i128)) + ((y as i128))) > ((u16::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u16) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_checked_add_signed() {
    // num.rs:152  <u16>::checked_add_signed   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: i16 = kani::any();
    let spec: Option<u16> = if ((((x as i128)) + ((y as i128))) > ((u16::MAX as i128))) || ((((x as i128)) + ((y as i128))) < (0i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u16) };
    assert_eq!(spec, x.checked_add_signed(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_checked_mul() {
    // num.rs:176  <u16>::checked_mul   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: Option<u16> = if (((x as i128)) * ((y as i128))) > ((u16::MAX as i128)) { None } else { Some((((x as i128)) * ((y as i128))) as u16) };
    assert_eq!(spec, x.checked_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_checked_sub() {
    // num.rs:164  <u16>::checked_sub   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: Option<u16> = if (((x as i128)) - ((y as i128))) < (0i128) { None } else { Some((((x as i128)) - ((y as i128))) as u16) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_saturating_add() {
    // num.rs:251  <u16>::saturating_add   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: u16 = if (((x as i128)) + ((y as i128))) > ((u16::MAX as i128)) { u16::MAX } else { (((x as i128)) + ((y as i128))) as u16 };
    assert_eq!(spec, x.saturating_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_saturating_mul() {
    // num.rs:275  <u16>::saturating_mul   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: u16 = if (((x as i128)) * ((y as i128))) > ((u16::MAX as i128)) { u16::MAX } else { (((x as i128)) * ((y as i128))) as u16 };
    assert_eq!(spec, x.saturating_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u16_saturating_sub() {
    // num.rs:263  <u16>::saturating_sub   (verus.git std_specs)
    let x: u16 = kani::any();
    let y: u16 = kani::any();
    let spec: u16 = if (((x as i128)) - ((y as i128))) < ((u16::MIN as i128)) { u16::MIN } else { (((x as i128)) - ((y as i128))) as u16 };
    assert_eq!(spec, x.saturating_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u32_checked_add() {
    // num.rs:140  <u32>::checked_add   (verus.git std_specs)
    let x: u32 = kani::any();
    let y: u32 = kani::any();
    let spec: Option<u32> = if (((x as i128)) + ((y as i128))) > ((u32::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u32) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u32_checked_add_signed() {
    // num.rs:152  <u32>::checked_add_signed   (verus.git std_specs)
    let x: u32 = kani::any();
    let y: i32 = kani::any();
    let spec: Option<u32> = if ((((x as i128)) + ((y as i128))) > ((u32::MAX as i128))) || ((((x as i128)) + ((y as i128))) < (0i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u32) };
    assert_eq!(spec, x.checked_add_signed(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u32_checked_sub() {
    // num.rs:164  <u32>::checked_sub   (verus.git std_specs)
    let x: u32 = kani::any();
    let y: u32 = kani::any();
    let spec: Option<u32> = if (((x as i128)) - ((y as i128))) < (0i128) { None } else { Some((((x as i128)) - ((y as i128))) as u32) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u32_saturating_add() {
    // num.rs:251  <u32>::saturating_add   (verus.git std_specs)
    let x: u32 = kani::any();
    let y: u32 = kani::any();
    let spec: u32 = if (((x as i128)) + ((y as i128))) > ((u32::MAX as i128)) { u32::MAX } else { (((x as i128)) + ((y as i128))) as u32 };
    assert_eq!(spec, x.saturating_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u32_saturating_sub() {
    // num.rs:263  <u32>::saturating_sub   (verus.git std_specs)
    let x: u32 = kani::any();
    let y: u32 = kani::any();
    let spec: u32 = if (((x as i128)) - ((y as i128))) < ((u32::MIN as i128)) { u32::MIN } else { (((x as i128)) - ((y as i128))) as u32 };
    assert_eq!(spec, x.saturating_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u64_checked_add() {
    // num.rs:140  <u64>::checked_add   (verus.git std_specs)
    let x: u64 = kani::any();
    let y: u64 = kani::any();
    let spec: Option<u64> = if (((x as i128)) + ((y as i128))) > ((u64::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u64) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u64_checked_add_signed() {
    // num.rs:152  <u64>::checked_add_signed   (verus.git std_specs)
    let x: u64 = kani::any();
    let y: i64 = kani::any();
    let spec: Option<u64> = if ((((x as i128)) + ((y as i128))) > ((u64::MAX as i128))) || ((((x as i128)) + ((y as i128))) < (0i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u64) };
    assert_eq!(spec, x.checked_add_signed(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u64_checked_sub() {
    // num.rs:164  <u64>::checked_sub   (verus.git std_specs)
    let x: u64 = kani::any();
    let y: u64 = kani::any();
    let spec: Option<u64> = if (((x as i128)) - ((y as i128))) < (0i128) { None } else { Some((((x as i128)) - ((y as i128))) as u64) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u64_saturating_add() {
    // num.rs:251  <u64>::saturating_add   (verus.git std_specs)
    let x: u64 = kani::any();
    let y: u64 = kani::any();
    let spec: u64 = if (((x as i128)) + ((y as i128))) > ((u64::MAX as i128)) { u64::MAX } else { (((x as i128)) + ((y as i128))) as u64 };
    assert_eq!(spec, x.saturating_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u64_saturating_sub() {
    // num.rs:263  <u64>::saturating_sub   (verus.git std_specs)
    let x: u64 = kani::any();
    let y: u64 = kani::any();
    let spec: u64 = if (((x as i128)) - ((y as i128))) < ((u64::MIN as i128)) { u64::MIN } else { (((x as i128)) - ((y as i128))) as u64 };
    assert_eq!(spec, x.saturating_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_add() {
    // num.rs:140  <u8>::checked_add   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: Option<u8> = if (((x as i128)) + ((y as i128))) > ((u8::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u8) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_add_signed() {
    // num.rs:152  <u8>::checked_add_signed   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: i8 = kani::any();
    let spec: Option<u8> = if ((((x as i128)) + ((y as i128))) > ((u8::MAX as i128))) || ((((x as i128)) + ((y as i128))) < (0i128)) { None } else { Some((((x as i128)) + ((y as i128))) as u8) };
    assert_eq!(spec, x.checked_add_signed(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_mul() {
    // num.rs:176  <u8>::checked_mul   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: Option<u8> = if (((x as i128)) * ((y as i128))) > ((u8::MAX as i128)) { None } else { Some((((x as i128)) * ((y as i128))) as u8) };
    assert_eq!(spec, x.checked_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_rem() {
    // num.rs:225  <u8>::checked_rem   (verus.git std_specs)
    let lhs: u8 = kani::any();
    let rhs: u8 = kani::any();
    let spec: Option<u8> = if ((rhs as i128)) == (0i128) { None } else { Some((((lhs).rem_euclid(rhs) as i128)) as u8) };
    assert_eq!(spec, lhs.checked_rem(rhs));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_rem_euclid() {
    // num.rs:238  <u8>::checked_rem_euclid   (verus.git std_specs)
    let lhs: u8 = kani::any();
    let rhs: u8 = kani::any();
    let spec: Option<u8> = if ((rhs as i128)) == (0i128) { None } else { Some((((lhs).rem_euclid(rhs) as i128)) as u8) };
    assert_eq!(spec, lhs.checked_rem_euclid(rhs));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_checked_sub() {
    // num.rs:164  <u8>::checked_sub   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: Option<u8> = if (((x as i128)) - ((y as i128))) < (0i128) { None } else { Some((((x as i128)) - ((y as i128))) as u8) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_is_multiple_of() {
    // num.rs:287  <u8>::is_multiple_of   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: bool = if ((y as i128)) == (0i128) { ((x as i128)) == (0i128) } else { (((x).rem_euclid(y) as i128)) == (0i128) };
    assert_eq!(spec, x.is_multiple_of(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_saturating_add() {
    // num.rs:251  <u8>::saturating_add   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: u8 = if (((x as i128)) + ((y as i128))) > ((u8::MAX as i128)) { u8::MAX } else { (((x as i128)) + ((y as i128))) as u8 };
    assert_eq!(spec, x.saturating_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_saturating_mul() {
    // num.rs:275  <u8>::saturating_mul   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: u8 = if (((x as i128)) * ((y as i128))) > ((u8::MAX as i128)) { u8::MAX } else { (((x as i128)) * ((y as i128))) as u8 };
    assert_eq!(spec, x.saturating_mul(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_u8_saturating_sub() {
    // num.rs:263  <u8>::saturating_sub   (verus.git std_specs)
    let x: u8 = kani::any();
    let y: u8 = kani::any();
    let spec: u8 = if (((x as i128)) - ((y as i128))) < ((u8::MIN as i128)) { u8::MIN } else { (((x as i128)) - ((y as i128))) as u8 };
    assert_eq!(spec, x.saturating_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_usize_checked_add() {
    // num.rs:140  <usize>::checked_add   (verus.git std_specs)
    let x: usize = kani::any();
    let y: usize = kani::any();
    let spec: Option<usize> = if (((x as i128)) + ((y as i128))) > ((usize::MAX as i128)) { None } else { Some((((x as i128)) + ((y as i128))) as usize) };
    assert_eq!(spec, x.checked_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_usize_checked_add_signed() {
    // num.rs:152  <usize>::checked_add_signed   (verus.git std_specs)
    let x: usize = kani::any();
    let y: isize = kani::any();
    let spec: Option<usize> = if ((((x as i128)) + ((y as i128))) > ((usize::MAX as i128))) || ((((x as i128)) + ((y as i128))) < (0i128)) { None } else { Some((((x as i128)) + ((y as i128))) as usize) };
    assert_eq!(spec, x.checked_add_signed(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_usize_checked_sub() {
    // num.rs:164  <usize>::checked_sub   (verus.git std_specs)
    let x: usize = kani::any();
    let y: usize = kani::any();
    let spec: Option<usize> = if (((x as i128)) - ((y as i128))) < (0i128) { None } else { Some((((x as i128)) - ((y as i128))) as usize) };
    assert_eq!(spec, x.checked_sub(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_usize_saturating_add() {
    // num.rs:251  <usize>::saturating_add   (verus.git std_specs)
    let x: usize = kani::any();
    let y: usize = kani::any();
    let spec: usize = if (((x as i128)) + ((y as i128))) > ((usize::MAX as i128)) { usize::MAX } else { (((x as i128)) + ((y as i128))) as usize };
    assert_eq!(spec, x.saturating_add(y));
}

#[cfg(kani)]
#[kani::proof]
fn gen_usize_saturating_sub() {
    // num.rs:263  <usize>::saturating_sub   (verus.git std_specs)
    let x: usize = kani::any();
    let y: usize = kani::any();
    let spec: usize = if (((x as i128)) - ((y as i128))) < ((usize::MIN as i128)) { usize::MIN } else { (((x as i128)) - ((y as i128))) as usize };
    assert_eq!(spec, x.saturating_sub(y));
}

